apiVersion: v1
kind: PersistentVolume
metadata:
  name: dictionary-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "dictionary-disk"