apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dictionary-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
