apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dictionary-claim
spec:
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 30Gi
